name: 'Rasa NLU Evaluation Results Comparison'
description: 'A GitHub action to compare Rasa NLU Evaluation results'
inputs:
  nlu_result_files:
    description: |
      The json report files that should be compared and the labels to associate with each of them. The report from which
      diffs should be calculated should be listed first. All results must be of the same type (e.g. intent classification,
      entity extraction). Labels for files should be unique.For example: `intent_report.json=1 second_intent_report.json=2`. Do
      not put spaces before or after the = sign. Label values with spaces should be put in double quotes. For example:
      `previous_results/DIETClassifier_report.json="Previous Stable Results" results/DIETClassifier_report.json="New
      Results"`
    required: true
    default: |
      previous_results/DIETClassifier_report.json="Previous Results" results/DIETClassifier_report.json="New Results"
  table_title:
    description: Title of HTML table.
    required: false
    default: Compared NLU Evaluation Results
  label_name:
    description: Type of labels predicted in the provided NLU result files e.g. 'intent', 'entity', 'retrieval intent'.
    required: false
    default: label
  html_outfile:
    description: File to which to write HTML table. File will be overwritten unless `append_table` is `true`.
    required: false
    default: formatted_compared_results.html
  append_table:
    description: |
      Whether to append the comparison table to the html output file, instead of overwriting it. 
      If not specified, html_outfile will be overwritten.
    required: false
  json_outfile:
    description: File to which to write combined json report (contents of all result files).
    required: false
    default: combined_results.json
  metrics_to_diff:
    description: Metrics to consider when determining changes across result sets.
    required: false
    default: support f1-score
  metrics_to_display:
    description: Metrics to display in resulting HTML table.
    required: false
    default: support f1-score
  sort_by_metric:
    description: Metrics to sort by (descending) in resulting HTML table.
    required: false
    default: support
  display_only_diff:
    description: |
      Display only labels with a change in at least one metric from the first listed result set. 
      If not specified, all labels will be displayed.
    required: false

branding:
  icon: 'message-square'  
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Checkout pull request HEAD commit instead of merge commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "${{ github.action_path }}"
      shell: bash 
    - name: What's in this dir?
      run: |
        echo $(ls)
      shell: bash
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      shell: bash
    - name: Run cross-val comparison for intents
      shell: bash
      run: |
        python compare_nlu_results.py \
            --nlu_result_files=${{ inputs.nlu_result_files }} \
            --table_title=${{ inputs.table_title }} \
            --lable_name=${{ inputs.label_name }} \
            --html_outfile=${{ inputs.html_outfile }} \
            --append_table=${{ inputs.append_table }} \
            --json_outfile=${{ inputs.json_outfile }} \
            --metrics_to_diff=${{ inputs.metrics_to_diff }} \
            --metrics_to_display=${{ inputs.metrics_to_display }} \
            --sort_by_metric=${{ inputs.sort_by_metric }} \
            --display_only_diff=${{ inputs.display_only_diff }}
