name: 'Rasa NLU Evaluation Results Comparison'
description: 'A GitHub action to compare Rasa NLU Evaluation results'
inputs:
  nlu_result_files:
    description: |
      The json report files that should be compared and the labels to associate with each of them. The report from which
      diffs should be calculated should be listed first. All results must be of the same type (e.g. intent classification,
      entity extraction). Labels for files should be unique.For example: `intent_report.json=1 second_intent_report.json=2`. Do
      not put spaces before or after the = sign. Label values with spaces should be put in double quotes. For example:
      `previous_results/DIETClassifier_report.json="Previous Stable Results" current_results/DIETClassifier_report.json="New
      Results"`
    required: true
  json_outfile:
    description: File to which to write combined json report (contents of all result files).
    required: false
    default: combined_results.json
  html_outfile:
    description: File to which to write HTML table. File will be overwritten unless `append_table` is specified.
    required: false
    default: formatted_compared_results.html
  append_table:
    description: |
      Whether to append the comparison table to the html output file, instead of overwriting it. 
      If not specified, html_outfile will be overwritten.
    required: false
  style_table:
    description: |
      Whether to add CSS style tags to the html table to highlight changed values. 
      Not compatible with Github Markdown format. Default is False.
    required: false
  table_title:
    description: Title of HTML table.
    required: false
    default: Compared NLU Evaluation Results
  label_name:
    description: Type of labels predicted in the provided NLU result files e.g. 'intent', 'entity', 'retrieval intent'.
    required: false
    default: label
  metrics_to_diff:
    description: Metrics to consider when determining changes across result sets.
    required: false
    default: support f1-score
  metrics_to_display:
    description: Metrics to display in resulting HTML table.
    required: false
    default: support f1-score
  metric_to_sort_by:
    description: Metrics to sort by (descending) in resulting HTML table.
    required: false
    default: support
  display_only_diff:
    description: |
      Display only labels with a change in at least one metric from the first listed result set. Default is false.
    required: false

branding:
  icon: 'message-square'  
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r "${{ github.action_path }}"/requirements.txt
      shell: bash
    - name: Set boolean options
      run: |
        case "${{ inputs.append_table }}" in
            "") echo "APPEND_TABLE=" >> $GITHUB_ENV ;;
            *) echo "APPEND_TABLE=--append_table" >> $GITHUB_ENV ;;
        esac

        case "${{ inputs.display_only_diff }}" in
           "") echo "DISPLAY_ONLY_DIFF=" >> $GITHUB_ENV ;;
            *) echo "DISPLAY_ONLY_DIFF=--display_only_diff" >> $GITHUB_ENV ;;
        esac

        case "${{ inputs.style_table }}" in
           "") echo "STYLE_TABLE=" >> $GITHUB_ENV ;;
            *) echo "STYLE_TABLE=--style_table" >> $GITHUB_ENV ;;
        esac
      shell: bash
    - name: Run Result Comparison
      shell: bash
      run: |
        export PYTHONPATH=$PYTHONPATH:${{ github.action_path }}
        python -m compare_nlu_results \
            --nlu_result_files ${{ inputs.nlu_result_files }} \
            --table_title "${{ inputs.table_title }}" \
            --label_name "${{ inputs.label_name }}" \
            --html_outfile "${{ inputs.html_outfile }}" \
            --json_outfile "${{ inputs.json_outfile }}" \
            --metrics_to_diff ${{ inputs.metrics_to_diff }} \
            --metrics_to_display ${{ inputs.metrics_to_display }} \
            --metric_to_sort_by "${{ inputs.metric_to_sort_by }}" \
            ${{ env.APPEND_TABLE }} \
            ${{ env.DISPLAY_ONLY_DIFF }} \
            ${{ env.STYLE_TABLE }}
